export const CONVIQ_SET_USER = 'CONVIQ_SET_USER';
export const CONVIQ_RESET = 'CONVIQ_RESET';

export const ANALYTICS_IDENTITY = 'ANALYTICS_IDENTITY';
export const ANALYTICS_RESET = 'ANALYTICS_RESET';
